export enum ControllersEnum {
    Classe = 'Classe',
    CondicaoMedica = 'CondicaoMedica',
    Evento = 'Evento',
    Funcao = 'Funcoes',
    Instrumento = 'Instrumento',
    Inscricao = 'Inscricao',
    Regiao = 'Regiao',
    Usuario = 'Usuario',
    Igreja = 'Igreja',
    QrCode = 'QRCode',	
    Dashboard = 'Dashboard',
    Checkin = 'Checkin',
    GestaoInscricao = 'GestaoInscricao',
    GestaoPagamento = 'GestaoPagamento',
    Visita = 'Visita',
    Relatorio = 'Relatorio',
}
