export enum CoresVisitaEnum {
  VERMELHA = 'Vermelha',
  VINHO = 'Vinho',
  ROSA = 'Rosa',
  SALMÃO = 'Salmão',
  LARANJA = 'Laranja',
  CORAL = 'Coral',
  AMARELO = 'Amarelo',
  OURO = 'Ouro',
  VERDE_CLARO = 'Verde Claro',
  VERDE = 'Verde',
  VERDE_ESCURO = 'Verde Escuro',
  AZUL_CLARO = 'Azul Claro',
  AZUL = 'Azul',
  AZUL_MARINHO = 'Azul Marinho',
  CIANO = 'Ciano',
  ROXA = 'Roxa',
  LILÁS = 'Lilás',
  MARROM = 'Marrom',
  BEGE = 'Bege',
  CINZA_CLARO = 'Cinza Claro',
  CINZA = 'Cinza',
  PRETA = 'Preta',
  BRANCA = 'Branca',
  PÉROLA = 'Pérola',
  TURQUESA = 'Turquesa'
}

export const CoresHexMap: Record<CoresVisitaEnum, string> = {
  [CoresVisitaEnum.VERMELHA]: '#FF0000',
  [CoresVisitaEnum.VINHO]: '#800000',
  [CoresVisitaEnum.ROSA]: '#FFC0CB',
  [CoresVisitaEnum.SALMÃO]: '#FA8072',
  [CoresVisitaEnum.LARANJA]: '#FFA500',
  [CoresVisitaEnum.CORAL]: '#FF7F50',
  [CoresVisitaEnum.AMARELO]: '#FFFF00',
  [CoresVisitaEnum.OURO]: '#FFD700',
  [CoresVisitaEnum.VERDE_CLARO]: '#90EE90',
  [CoresVisitaEnum.VERDE]: '#008000',
  [CoresVisitaEnum.VERDE_ESCURO]: '#006400',
  [CoresVisitaEnum.AZUL_CLARO]: '#ADD8E6',
  [CoresVisitaEnum.AZUL]: '#0000FF',
  [CoresVisitaEnum.AZUL_MARINHO]: '#000080',
  [CoresVisitaEnum.CIANO]: '#00FFFF',
  [CoresVisitaEnum.ROXA]: '#800080',
  [CoresVisitaEnum.LILÁS]: '#C8A2C8',
  [CoresVisitaEnum.MARROM]: '#8B4513',
  [CoresVisitaEnum.BEGE]: '#F5F5DC',
  [CoresVisitaEnum.CINZA_CLARO]: '#D3D3D3',
  [CoresVisitaEnum.CINZA]: '#808080',
  [CoresVisitaEnum.PRETA]: '#000000',
  [CoresVisitaEnum.BRANCA]: '#FFFFFF',
  [CoresVisitaEnum.PÉROLA]: '#F8F6F0',
  [CoresVisitaEnum.TURQUESA]: '#40E0D0'
};
